export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST" as const;
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS" as const;
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED" as const;
export const INCREMENT_INGREDIENT_COUNT = "INCREMENT_INGREDIENT_COUNT" as const;
export const DECREMENT_INGREDIENT_COUNT = "DECREMENT_INGREDIENT_COUNT" as const;
export const RESET_INGREDIENT_COUNTS = "RESET_INGREDIENT_COUNTS" as const;
