export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST" as const;
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS" as const;
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE" as const;
