export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST" as const;
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS" as const;
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE" as const;
